// Bảng dữ liệu và thông số Võ Học Môn Phái - Cửu Châu Kiếm Vũ (Có Cây Kỹ Năng & Cấp Độ Kỹ Năng)

const SKILLS = {
  // --- HOA SƠN KIẾM PHÁI ---
  hs_1: {
    id: 'hs_1',
    name: 'Tật Phong Kiếm Khí',
    sect: 'huashan',
    icon: 'skill_1.png',
    maxLevel: 10,
    baseCooldown: 1800,
    baseMpCost: 18,
    baseDamageMul: 1.5,
    dmgPerLevel: 0.15,
    cdReducePerLevel: 60,
    type: 'projectile',
    projectileWidth: 35,
    projectileLength: 70,
    color: '#38bdf8',
    desc: 'Phóng ra một đạo kiếm khí lam sắc sắc bén xé toạc không trung, xuyên thấu mục tiêu.'
  },
  hs_2: {
    id: 'hs_2',
    name: 'Vạn Kiếm Quy Tông',
    sect: 'huashan',
    icon: 'skill_2.png',
    maxLevel: 10,
    baseCooldown: 6000,
    baseMpCost: 50,
    baseDamageMul: 0.8,
    dmgPerLevel: 0.1,
    cdReducePerLevel: 150,
    radius: 200,
    duration: 1800,
    type: 'aoe_storm',
    color: '#fbbf24',
    desc: 'Ngưng tụ vạn thanh kiếm khí hoàng kim từ hư không, giáng bão kiếm liên hoàn xuống khu vực đối phương.'
  },
  hs_3: {
    id: 'hs_3',
    name: 'Tử Hà Hộ Thể',
    sect: 'huashan',
    icon: 'skill_6.png',
    maxLevel: 10,
    baseCooldown: 8000,
    baseMpCost: 40,
    baseShieldMul: 0.35,
    shieldPerLevel: 0.05,
    duration: 5000,
    type: 'buff_shield',
    color: '#a855f7',
    desc: 'Vận chuyển Tử Hà Thần Công hộ thể, ngưng tụ chân khí hộ thuẫn kháng cự sát thương và hồi phục khí huyết.'
  },
  hs_4: {
    id: 'hs_4',
    name: 'Thiên Ngoại Phi Tiên',
    sect: 'huashan',
    icon: 'skill_8.png',
    maxLevel: 10,
    baseCooldown: 12000,
    baseMpCost: 85,
    baseDamageMul: 3.2,
    dmgPerLevel: 0.3,
    cdReducePerLevel: 300,
    range: 420,
    critBonus: 0.45,
    type: 'dash_slash',
    color: '#60a5fa',
    desc: 'Tuyệt kỹ trấn phái: Hóa thân thành phi kiếm xuyên không trảm kích đối thủ với uy lực bạo kích kinh thiên.'
  },

  // Kỹ năng bị động Hoa Sơn
  hs_passive_1: {
    id: 'hs_passive_1',
    name: 'Độc Cô Kiếm Ý',
    sect: 'huashan',
    icon: 'skill_4.png',
    maxLevel: 10,
    type: 'passive',
    critBonusPerLevel: 0.03, // +3% Bạo kích mỗi cấp
    atkBonusPerLevel: 12,    // +12 Công mỗi cấp
    desc: 'Tâm kiếm hợp nhất, gia tăng vĩnh viễn Tỷ lệ Bạo Kích và Sát Thương Ngoại Công.'
  },

  // --- TIÊU DAO TIÊN TÔNG ---
  xy_1: {
    id: 'xy_1',
    name: 'Thiên Sơn Lục Dương',
    sect: 'xiaoyao',
    icon: 'skill_9.png',
    maxLevel: 10,
    baseCooldown: 2000,
    baseMpCost: 22,
    baseDamageMul: 1.6,
    dmgPerLevel: 0.16,
    cdReducePerLevel: 70,
    type: 'projectile',
    projectileWidth: 40,
    projectileLength: 60,
    color: '#34d399',
    desc: 'Ngưng tụ lục dương chưởng kình, phóng ra luồng chưởng phong ngọc bích cực mạnh phá hủy phòng ngự.'
  },
  xy_2: {
    id: 'xy_2',
    name: 'Bắc Minh Thần Công',
    sect: 'xiaoyao',
    icon: 'skill_5.png',
    maxLevel: 10,
    baseCooldown: 7000,
    baseMpCost: 55,
    baseDamageMul: 0.65,
    dmgPerLevel: 0.08,
    cdReducePerLevel: 180,
    radius: 220,
    duration: 2500,
    siphonRate: 0.3,
    type: 'vortex',
    color: '#818cf8',
    desc: 'Khởi động Bắc Minh Hải Nhãn, tạo lốc xoáy chân khí hút kẻ địch vào tâm xoáy và hấp thụ nội lực sinh mệnh.'
  },
  xy_3: {
    id: 'xy_3',
    name: 'Bát Quái Hộ Trận',
    sect: 'xiaoyao',
    icon: 'skill_3.png',
    maxLevel: 10,
    baseCooldown: 9000,
    baseMpCost: 45,
    duration: 6000,
    reflectMul: 0.35,
    reflectPerLevel: 0.03,
    type: 'buff_formation',
    color: '#eab308',
    desc: 'Triệu hoán Bát Quái Đồ chuyển động dưới chân, phản hồi sát thương nhận vào cho kẻ tấn công.'
  },
  xy_4: {
    id: 'xy_4',
    name: 'Lăng Ba Tuyệt Ảo',
    sect: 'xiaoyao',
    icon: 'skill_7.png',
    maxLevel: 10,
    baseCooldown: 11000,
    baseMpCost: 80,
    baseDamageMul: 2.9,
    dmgPerLevel: 0.28,
    cdReducePerLevel: 250,
    radius: 280,
    type: 'phantom_burst',
    color: '#10b981',
    desc: 'Lăng ba phiêu dật, phân thân tàn ảnh chém liên hoàn các mục tiêu xung quanh rồi hồi phục đại lượng sinh lực.'
  },

  // Kỹ năng bị động Tiêu Dao
  xy_passive_1: {
    id: 'xy_passive_1',
    name: 'Tiêu Dao Du',
    sect: 'xiaoyao',
    icon: 'skill_4.png',
    maxLevel: 10,
    type: 'passive',
    dodgeBonusPerLevel: 0.02, // +2% Né tránh mỗi cấp
    speedBonusPerLevel: 8,    // +8 Thân pháp mỗi cấp
    desc: 'Nhẹ nhàng như mây gió, gia tăng vĩnh viễn Khả năng Né Tránh và Tốc Độ Di Chuyển.'
  },

  // --- THIẾU LÂM TỰ (NGOẠI CÔNG PHÒNG THỦ - TANKER KIM CANG) ---
  sl_1: {
    id: 'sl_1',
    name: 'La Hán Côn Pháp',
    sect: 'shaolin',
    icon: 'skill_sl_1.png',
    maxLevel: 10,
    baseCooldown: 1800,
    baseMpCost: 16,
    baseDamageMul: 1.55,
    dmgPerLevel: 0.16,
    cdReducePerLevel: 60,
    type: 'projectile',
    projectileWidth: 42,
    projectileLength: 68,
    color: '#f59e0b',
    desc: 'Vung Côn gầm vang, phóng ra luồng kim quang cương mãnh chấn nát phòng ngự đối phương.'
  },
  sl_2: {
    id: 'sl_2',
    name: 'Kim Cang Phục Ma Trận',
    sect: 'shaolin',
    icon: 'skill_sl_2.png',
    maxLevel: 10,
    baseCooldown: 6500,
    baseMpCost: 45,
    baseDamageMul: 0.75,
    dmgPerLevel: 0.09,
    cdReducePerLevel: 160,
    radius: 230,
    duration: 2200,
    type: 'aoe_stomp',
    color: '#d97706',
    desc: 'Dậm đất giáng thế Kim Cang, tạo vòng Phật Quang chữ Vạn chấn kích và làm chậm toàn bộ kẻ địch.'
  },
  sl_3: {
    id: 'sl_3',
    name: 'Kim Cang Bất Hoại Thể',
    sect: 'shaolin',
    icon: 'skill_sl_3.png',
    maxLevel: 10,
    baseCooldown: 9500,
    baseMpCost: 50,
    baseShieldMul: 0.50,
    shieldPerLevel: 0.06,
    reflectMul: 0.35,
    duration: 6000,
    type: 'buff_shield',
    color: '#fbbf24',
    desc: 'Vận chuyển La Hán Thần Công, hóa thân thành tượng vàng bất hoại, hấp thụ sát thương cực lớn và phản đòn 35% sát thương nhận vào.'
  },
  sl_4: {
    id: 'sl_4',
    name: 'Sư Tử Hống Thần Công',
    sect: 'shaolin',
    icon: 'skill_sl_4.png',
    maxLevel: 10,
    baseCooldown: 12500,
    baseMpCost: 85,
    baseDamageMul: 3.4,
    dmgPerLevel: 0.32,
    cdReducePerLevel: 300,
    radius: 320,
    type: 'ultimate_roar',
    color: '#ea580c',
    desc: 'Tuyệt kỹ đệ nhất Phật môn: Tiếng gầm vang dội đất trời, chấn động kinh mạch toàn bộ kẻ thù trong diện rộng với uy lực long trời lở đất.'
  },
  sl_passive_1: {
    id: 'sl_passive_1',
    name: 'Dịch Cân Tẩy Tủy',
    sect: 'shaolin',
    icon: 'skill_sl_1.png',
    maxLevel: 10,
    type: 'passive',
    hpBonusPerLevel: 250,    // +250 Khí Huyết mỗi cấp
    defBonusPerLevel: 16,    // +16 Ngoại Thủ mỗi cấp
    desc: 'Khổ luyện Dịch Cân Kinh, thân thể đúc bằng đồng thép, gia tăng vĩnh viễn Lượng Khí Huyết và Khả năng Phòng Ngự.'
  },

  // --- VÕ ĐANG PHÁI (NỘI CÔNG TẦM XA - THÁI CỰC KIẾM TRẬN) ---
  wd_1: {
    id: 'wd_1',
    name: 'Thái Cực Thần Kiếm',
    sect: 'wudang',
    icon: 'skill_wd_1.png',
    maxLevel: 10,
    baseCooldown: 1900,
    baseMpCost: 20,
    baseDamageMul: 1.65,
    dmgPerLevel: 0.17,
    cdReducePerLevel: 70,
    type: 'projectile',
    projectileWidth: 38,
    projectileLength: 75,
    color: '#38bdf8',
    desc: 'Phóng ra song đạo kiếm khí Âm Dương xoay chuyển, gây sát thương nội công xuyên thấu kẻ địch.'
  },
  wd_2: {
    id: 'wd_2',
    name: 'Lưỡng Nghi Kiếm Trận',
    sect: 'wudang',
    icon: 'skill_wd_2.png',
    maxLevel: 10,
    baseCooldown: 6000,
    baseMpCost: 48,
    baseDamageMul: 0.78,
    dmgPerLevel: 0.09,
    cdReducePerLevel: 150,
    radius: 210,
    duration: 2000,
    type: 'aoe_storm',
    color: '#0284c7',
    desc: 'Triệu hoán Lưỡng Nghi Bát Quái Kiếm Trận từ trên trời rơi xuống, dội bão kiếm liên hoàn tiêu diệt quân địch.'
  },
  wd_3: {
    id: 'wd_3',
    name: 'Tọa Vong Vô Ngã',
    sect: 'wudang',
    icon: 'skill_wd_3.png',
    maxLevel: 10,
    baseCooldown: 9000,
    baseMpCost: 40,
    baseShieldMul: 0.40,
    shieldPerLevel: 0.05,
    duration: 6000,
    type: 'buff_shield',
    color: '#6366f1',
    desc: 'Hóa hư vô thành thực thể, ngưng tụ Thái Cực Chân Khí Hộ Thể, dùng Nội Lực hóa giải mọi sát thương chí mạng.'
  },
  wd_4: {
    id: 'wd_4',
    name: 'Vạn Kiếm Triều Tông',
    sect: 'wudang',
    icon: 'skill_wd_4.png',
    maxLevel: 10,
    baseCooldown: 12000,
    baseMpCost: 90,
    baseDamageMul: 3.3,
    dmgPerLevel: 0.30,
    cdReducePerLevel: 280,
    radius: 350,
    type: 'ultimate_swords',
    color: '#06b6d4',
    desc: 'Chân Vũ Thần Kiếm xuất vỏ: Triệu hồi vạn đạo kiếm quang từ chín tầng trời giáng xuống nghiền nát quân thù.'
  },
  wd_passive_1: {
    id: 'wd_passive_1',
    name: 'Thuần Dương Vô Cực',
    sect: 'wudang',
    icon: 'skill_wd_1.png',
    maxLevel: 10,
    type: 'passive',
    atkBonusPerLevel: 15,    // +15 Công mỗi cấp
    mpBonusPerLevel: 120,    // +120 Nội Lực mỗi cấp
    desc: 'Tu luyện Thuần Dương Chân Khí, gia tăng vĩnh viễn Sức Tấn Công và Lượng Nội Lực của bản thân.'
  },

  // ================= 4 MÔN PHÁI TU TIÊN (CẤP 30 MỞ KHÓA) =================
  // 1. THÁI THANH TIÊN TÔNG (ĐẠO GIÁO)
  tt_1: {
    id: 'tt_1',
    name: 'Lôi Đình Kiếm Trảm',
    sect: 'dao',
    icon: 'skill_1.png',
    maxLevel: 10,
    baseCooldown: 3500,
    baseMpCost: 65,
    baseDamageMul: 3.5,
    dmgPerLevel: 0.35,
    cdReducePerLevel: 80,
    type: 'projectile',
    color: '#00e5ff',
    desc: 'Phóng ra vạn đạo kiếm khí sấm sét tiên gia xuyên thấu mục tiêu.'
  },
  tt_2: {
    id: 'tt_2',
    name: 'Thái Cực Linh Trận',
    sect: 'dao',
    icon: 'skill_2.png',
    maxLevel: 10,
    baseCooldown: 7500,
    baseMpCost: 110,
    baseDamageMul: 2.2,
    dmgPerLevel: 0.25,
    cdReducePerLevel: 150,
    radius: 260,
    duration: 3500,
    type: 'aoe_storm',
    color: '#38bdf8',
    desc: 'Thi triển Thái Cực Bát Quái trận, khóa chân quái và giáng kiếm trận liên hoàn.'
  },
  tt_3: {
    id: 'tt_3',
    name: 'Cửu Thiên Huyền Lôi',
    sect: 'dao',
    icon: 'skill_3.png',
    maxLevel: 10,
    baseCooldown: 14000,
    baseMpCost: 160,
    baseDamageMul: 4.8,
    dmgPerLevel: 0.45,
    cdReducePerLevel: 250,
    radius: 350,
    type: 'thunder_aoe',
    color: '#818cf8',
    desc: 'Triệu hồi thiên lôi cuồng nộ giáng xuống toàn màn hình thiêu rụi quân thù.'
  },
  tt_4: {
    id: 'tt_4',
    name: 'Vạn Kiếm Quy Tông',
    sect: 'dao',
    icon: 'skill_4.png',
    maxLevel: 10,
    baseCooldown: 22000,
    baseMpCost: 240,
    baseDamageMul: 8.5,
    dmgPerLevel: 0.8,
    cdReducePerLevel: 400,
    radius: 450,
    type: 'ultimate_swords',
    color: '#e0e7ff',
    desc: 'Đỉnh cao kiếm đạo: triệu hồi 10,000 thanh tiên kiếm thanh tẩy cõi hồng hoang.'
  },

  // 2. PHẠN THIÊN THIỀN TỰ (PHẬT GIÁO)
  pt_1: {
    id: 'pt_1',
    name: 'Kim Cang Hàng Ma Quyền',
    sect: 'buddha',
    icon: 'skill_sl_1.png',
    maxLevel: 10,
    baseCooldown: 3500,
    baseMpCost: 60,
    baseDamageMul: 3.2,
    dmgPerLevel: 0.3,
    cdReducePerLevel: 70,
    type: 'melee_aoe',
    color: '#fbbf24',
    desc: 'Quyền kình Phật môn nghiền nát hộ giáp đối phương, gây choáng 2s.'
  },
  pt_2: {
    id: 'pt_2',
    name: 'Bồ Đề Thanh Tâm Chú',
    sect: 'buddha',
    icon: 'skill_sl_2.png',
    maxLevel: 10,
    baseCooldown: 12000,
    baseMpCost: 140,
    baseShieldMul: 0.65,
    shieldPerLevel: 0.08,
    duration: 8000,
    type: 'buff_shield',
    color: '#f59e0b',
    desc: 'Hồi phục 35% HP tối đa và tạo khiên Kim Chung hộ thể chặn đứng vạn kích.'
  },
  pt_3: {
    id: 'pt_3',
    name: 'Như Lai Thần Chưởng',
    sect: 'buddha',
    icon: 'skill_sl_3.png',
    maxLevel: 10,
    baseCooldown: 12000,
    baseMpCost: 170,
    baseDamageMul: 5.2,
    dmgPerLevel: 0.5,
    cdReducePerLevel: 220,
    radius: 300,
    type: 'holy_palm',
    color: '#ffd700',
    desc: 'Chưởng ấn hoàng kim khổng lồ từ chín tầng mây dội xuống đập tan quân thù.'
  },
  pt_4: {
    id: 'pt_4',
    name: 'Vạn Phật Triều Tông',
    sect: 'buddha',
    icon: 'skill_sl_4.png',
    maxLevel: 10,
    baseCooldown: 22000,
    baseMpCost: 250,
    baseDamageMul: 7.5,
    dmgPerLevel: 0.75,
    cdReducePerLevel: 350,
    radius: 420,
    type: 'aoe_storm',
    color: '#fef08a',
    desc: 'Phật quang vạn trượng chiếu rọi tam giới, thiêu đốt tà ma thành tro bụi.'
  },

  // 3. U MINH MA TÔNG (MA GIÁO)
  um_1: {
    id: 'um_1',
    name: 'Thiên Ma Xé Rách',
    sect: 'demon',
    icon: 'skill_5.png',
    maxLevel: 10,
    baseCooldown: 3500,
    baseMpCost: 70,
    baseDamageMul: 3.8,
    dmgPerLevel: 0.38,
    cdReducePerLevel: 80,
    type: 'projectile',
    color: '#ef4444',
    desc: 'Nhát chém ma đao xé rách không gian, gây xuất huyết 10% HP kẻ thù.'
  },
  um_2: {
    id: 'um_2',
    name: 'Huyết Ma Tế Đàn',
    sect: 'demon',
    icon: 'skill_6.png',
    maxLevel: 10,
    baseCooldown: 9000,
    baseMpCost: 130,
    baseDamageMul: 3.0,
    dmgPerLevel: 0.3,
    cdReducePerLevel: 160,
    radius: 280,
    type: 'vortex',
    color: '#b91c1c',
    desc: 'Hút máu tất cả kẻ địch trong phạm vi, hồi phục 60% sát thương thành sinh lực bản thân.'
  },
  um_3: {
    id: 'um_3',
    name: 'U Minh Quỷ Diễm',
    sect: 'demon',
    icon: 'skill_7.png',
    maxLevel: 10,
    baseCooldown: 13000,
    baseMpCost: 180,
    baseDamageMul: 5.5,
    dmgPerLevel: 0.55,
    cdReducePerLevel: 240,
    radius: 320,
    type: 'fire_aoe',
    color: '#991b1b',
    desc: 'Biển lửa địa ngục u minh thiêu đốt mục tiêu liên tục trong 6s.'
  },
  um_4: {
    id: 'um_4',
    name: 'Ma Hoàng Thần Biến',
    sect: 'demon',
    icon: 'skill_8.png',
    maxLevel: 10,
    baseCooldown: 25000,
    baseMpCost: 260,
    baseDamageMul: 8.8,
    dmgPerLevel: 0.85,
    cdReducePerLevel: 400,
    radius: 380,
    type: 'ultimate_swords',
    color: '#450a0a',
    desc: 'Hóa thân Ma Hoàng cuồng nộ: Tăng 100% Công, 50% Hút máu, bộc phát sát thương cực đại.'
  },

  // 4. VẠN YÊU THÁNH ĐIỆN (YÊU TỘC)
  vy_1: {
    id: 'vy_1',
    name: 'Thái Cổ Long Trảo',
    sect: 'beast',
    icon: 'skill_xy_1.png',
    maxLevel: 10,
    baseCooldown: 3200,
    baseMpCost: 65,
    baseDamageMul: 3.6,
    dmgPerLevel: 0.35,
    cdReducePerLevel: 80,
    type: 'melee_aoe',
    color: '#10b981',
    desc: 'Móng vuốt thần long xé toạc hộ giáp, bỏ qua 50% phòng thủ mục tiêu.'
  },
  vy_2: {
    id: 'vy_2',
    name: 'Thiên Hồ Ảo Ảnh Trận',
    sect: 'beast',
    icon: 'skill_xy_2.png',
    maxLevel: 10,
    baseCooldown: 7500,
    baseMpCost: 110,
    baseDamageMul: 3.2,
    dmgPerLevel: 0.3,
    cdReducePerLevel: 140,
    radius: 260,
    type: 'aoe_storm',
    color: '#34d399',
    desc: 'Triệu hồi 9 ảo ảnh cửu vĩ hồ tấn công chớp nhoáng xé nát kẻ địch.'
  },
  vy_3: {
    id: 'vy_3',
    name: 'Vạn Độc Hủ Cốt Yên',
    sect: 'beast',
    icon: 'skill_xy_3.png',
    maxLevel: 10,
    baseCooldown: 11000,
    baseMpCost: 160,
    baseDamageMul: 4.6,
    dmgPerLevel: 0.45,
    cdReducePerLevel: 200,
    radius: 300,
    type: 'poison_aoe',
    color: '#059669',
    desc: 'Phun làn khói độc yêu giới ăn mòn sinh lực quái liên tục theo thời gian.'
  },
  vy_4: {
    id: 'vy_4',
    name: 'Yêu Hoàng Thức Tỉnh',
    sect: 'beast',
    icon: 'skill_xy_4.png',
    maxLevel: 10,
    baseCooldown: 20000,
    baseMpCost: 240,
    baseDamageMul: 8.0,
    dmgPerLevel: 0.8,
    cdReducePerLevel: 350,
    radius: 400,
    type: 'ultimate_swords',
    color: '#a7f3d0',
    desc: 'Bộc phát sức mạnh Hồng Hoang Thượng Cổ Thần Thú, 100% bạo kích chí mạng.'
  }
};

module.exports = { SKILLS };

